
default_platform(:android)

platform :android do
  desc "lane for android firebase app distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --no-tree-shake-icons"
    firebase_app_distribution(
            app: "1:362445327288:android:45fc753b060579cd21dd4d",
            firebase_cli_token:"1//03NyccJyG-pCzCgYIARAAGAMSNwF-L9IrUcw_D7XSZhMq_Pulsvx_qxwNyP2aiHjfjHpvqY0Hwf2ixVcnPAgbRO1THqcvisgIh_4",
            android_artifact_type: "APK",
            android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
            testers: "mohamedelbiomy336@gmail.com",
            release_notes: "new version released home screen"
        )
  end
end
